### ISSUE TITLE
real time performance metrics in the cloudbroker gui

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/selfhealing#24]
## description

integrate https://arya.maxux.net/monitoring/table/?endpoint=be-g8-4 into the GUI
## why

grafana is good for aggregate performance - but real time metrics are needed to zoom into a problem
## how

make a menu underneath statistics:
- historical statistics (goes to grafana reports)
- real time statistics (goes to real time dashboard)

when clicking on real time statistics you go to the dashboard 

allow filtering so specific nodes / group of nodes  can be selected

retain the colour thresholds as defined in https://arya.maxux.net/monitoring/table/?endpoint=be-g8-4

**Comment by FastGeert** [comment]
Seems not to be relevant anymore.
